version: 2
updates:
  - package-ecosystem: gomod
    directory: /go/service
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /go/service
    schedule:
      interval: weekly
